package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// FindRunByID resolves a Run entity referenced by a supergraph router by its
// @key(id). This is what lets other subgraphs (evals, Draw) attach fields to a
// run they only know by id.
func (r *entityResolver) FindRunByID(ctx context.Context, id string) (*Run, error) {
	got, err := r.Store.Get(ctx, id)
	if err != nil {
		return nil, nil
	}
	return toRun(got), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
