// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Query struct {
}

// Loupe's subgraph: typed, cold-path reads over agent runs.
//
// This is a federation subgraph. Run is an entity (note @key), so a supergraph
// router can reference a run by id and other subgraphs (evals, Draw) can extend it
// with their own fields. The live, high-rate trace does NOT go through GraphQL: it
// streams over Server-Sent Events at /runs/{id}/stream, the same way you would not
// push a 60fps feed through a GraphQL subscription. GraphQL here is only for the
// typed reads: look a run up, list recent runs.
type Run struct {
	// Run id; also the SSE stream path /runs/<id>/stream.
	ID     string    `json:"id"`
	Task   string    `json:"task"`
	Status RunStatus `json:"status"`
	// Set only when the run failed.
	Error *string `json:"error,omitempty"`
	// Every step the run has taken, in order.
	Steps []*Step `json:"steps"`
}

func (Run) IsEntity() {}

// One entry in a run's timeline. Only the fields relevant to its kind are set.
type Step struct {
	ID      int      `json:"id"`
	Kind    StepKind `json:"kind"`
	Thought *string  `json:"thought,omitempty"`
	Tool    *string  `json:"tool,omitempty"`
	Input   *string  `json:"input,omitempty"`
	Output  *string  `json:"output,omitempty"`
	IsError bool     `json:"isError"`
	Answer  *string  `json:"answer,omitempty"`
}

type RunStatus string

const (
	RunStatusPending   RunStatus = "PENDING"
	RunStatusRunning   RunStatus = "RUNNING"
	RunStatusSucceeded RunStatus = "SUCCEEDED"
	RunStatusFailed    RunStatus = "FAILED"
)

var AllRunStatus = []RunStatus{
	RunStatusPending,
	RunStatusRunning,
	RunStatusSucceeded,
	RunStatusFailed,
}

func (e RunStatus) IsValid() bool {
	switch e {
	case RunStatusPending, RunStatusRunning, RunStatusSucceeded, RunStatusFailed:
		return true
	}
	return false
}

func (e RunStatus) String() string {
	return string(e)
}

func (e *RunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RunStatus", str)
	}
	return nil
}

func (e RunStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StepKind string

const (
	StepKindThink    StepKind = "THINK"
	StepKindToolCall StepKind = "TOOL_CALL"
	StepKindObserve  StepKind = "OBSERVE"
	StepKindFinal    StepKind = "FINAL"
)

var AllStepKind = []StepKind{
	StepKindThink,
	StepKindToolCall,
	StepKindObserve,
	StepKindFinal,
}

func (e StepKind) IsValid() bool {
	switch e {
	case StepKindThink, StepKindToolCall, StepKindObserve, StepKindFinal:
		return true
	}
	return false
}

func (e StepKind) String() string {
	return string(e)
}

func (e *StepKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StepKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StepKind", str)
	}
	return nil
}

func (e StepKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StepKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StepKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
