package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// Run is the resolver for the run field.
func (r *queryResolver) Run(ctx context.Context, id string) (*Run, error) {
	got, err := r.Store.Get(ctx, id)
	if err != nil {
		return nil, nil // an unknown id is null, not an error
	}
	return toRun(got), nil
}

// Runs is the resolver for the runs field.
func (r *queryResolver) Runs(ctx context.Context, limit *int) ([]*Run, error) {
	n := 20
	if limit != nil {
		n = *limit
	}
	runs, err := r.Store.List(ctx, n)
	if err != nil {
		return nil, err
	}
	out := make([]*Run, 0, len(runs))
	for _, got := range runs {
		out = append(out, toRun(got))
	}
	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
